INSERT INTO t_questions (question_id, question)VALUES (1, 'Quel système d\'exploitation utilisez-vous le plus à la maison ?');
INSERT INTO t_questions (question_id, question)VALUES (2, 'Quel système d\'exploitation utilisez-vous le plus à l\'université ?');
INSERT INTO t_questions (question_id, question)VALUES (3, 'Combien d\'heures par semaine utilisez-vous Windows ?');
INSERT INTO t_questions (question_id, question)VALUES (4, 'Combien d\'heures par semaine utilisez-vous Unix ou Linux ?');
INSERT INTO t_questions (question_id, question)VALUES (5, 'Combien d\'heures par semaine utilisez-vous Mac OS X ?');
INSERT INTO t_questions (question_id, question)VALUES (6, 'Si vous travaillez à temps partiel, combien d\'heures par semaine travaillez-vous ?');
INSERT INTO t_questions (question_id, question)VALUES (7, 'Si vous avez un travail à temps partiel, est-ce un emploi dans le domaine de l\'informatique ?');
INSERT INTO t_questions (question_id, question)VALUES (8, 'Combien d\'heures par semaine consacrez-vous à vos études en dehors des heures de cours ? (projets, étude, etc.)');
INSERT INTO t_questions (question_id, question)VALUES (9, 'À quel type de baccalauréat en informatique êtes-vous inscrit ?');
INSERT INTO t_questions (question_id, question)VALUES (10, 'En quelle année du baccalauréat êtes-vous ?');
INSERT INTO t_questions (question_id, question)VALUES (11, 'Possédez-vous un produit Apple ? Si oui lequel ?');
INSERT INTO t_questions (question_id, question)VALUES (12, 'Quels langages utilisez-vous sur une base régulière ?');
INSERT INTO t_questions (question_id, question)VALUES (13, 'Quels sont vos langages préférés ?');
INSERT INTO t_questions (question_id, question)VALUES (14, 'Avez-vous déjà pensé à écrire un article scientifique ?');
INSERT INTO t_questions (question_id, question)VALUES (15, 'Quel navigateur web utilisez-vous principalement ?');
INSERT INTO t_questions (question_id, question)VALUES (16, 'Est-ce que vous avez l\'habitude de faire des calculs informatiques nécessitant une haute performance (cluster, système distribué, etc.) ?');
INSERT INTO t_questions (question_id, question)VALUES (17, 'Comment évaluez-vous l\'implication des étudiants du Département d\'informatique sur des projets collaboratifs ?');
INSERT INTO t_questions (question_id, question)VALUES (18, 'Utilisez-vous un ou des systèmes de gestion de version (version control system) pour le développement ?');
INSERT INTO t_questions (question_id, question)VALUES (19, 'Si vous utilisez un ou des systèmes de gestion de version, lesquels ?');
INSERT INTO t_questions (question_id, question)VALUES (20, 'Selon vous lequel des systèmes suivants est le plus ouvert au grand public à la fois dans le sens de la facilité et de la liberté d\'utilisation ?');
INSERT INTO t_questions (question_id, question)VALUES (21, 'Pensez-vous qu\'une étudiante ou qu\'un étudiant en informatique devrait avoir des connaissances de base de Linux ?');
INSERT INTO t_questions (question_id, question)VALUES (22, 'Pensez-vous que le gaming (jeux vidéo) a un avenir sous Linux?');
INSERT INTO t_questions (question_id, question)VALUES (23, 'Pensez-vous que Linux soit uniquement utilisable par un cercle restreint d\'individus ayant certaines connaissances ?');
INSERT INTO t_questions (question_id, question)VALUES (24, 'Selon vous qui est Richard Stallman ?');
INSERT INTO t_questions (question_id, question)VALUES (25, 'Que pensez-vous du fait d\'imposer un apprentissage informatique basé sur des systèmes propriétaires aux enfants dès l\'école primaire?');
INSERT INTO t_questions (question_id, question)VALUES (26, 'Pensez-vous qu\'il serait profitable pour les enfants d\'être exposés à Linux dès l\'école primaire ?');
INSERT INTO t_questions (question_id, question)VALUES (27, 'Avez-vous suffisamment d\'information sur le contenu des cours optionnels (informatique) pour faire un choix éclairé ?');
INSERT INTO t_questions (question_id, question)VALUES (28, 'Quels sont les critères sur lesquels vous vous basez dans le choix des cours à option de 3ème et 4ème années en informatique ?');
INSERT INTO t_questions (question_id, question)VALUES (29, 'Saviez-vous qu\'il y a un cluster (machine parallèle) au département ?');
INSERT INTO t_questions (question_id, question)VALUES (30, 'Pensez-vous qu\'installer Linux en dual boot avec Windows sur les ordinateurs du département serait une bonne idée ?');
INSERT INTO t_questions (question_id, question)VALUES (31, 'Quels langages aimeriez-vous apprendre ?');
INSERT INTO t_questions (question_id, question)VALUES (32, 'Quels langages aimeriez-vous éviter?');
INSERT INTO t_questions (question_id, question)VALUES (33, 'Quels sujets suivants vous intéressent pour d\'éventuels séminaires au Département d\'informatique ?');
INSERT INTO t_questions (question_id, question)VALUES (34, 'De quelle façon avez-vous pris connaissance du programme d\'informatique de l\'Université de Moncton ?');
INSERT INTO t_questions (question_id, question)VALUES (35, 'Quand avez-vous pris la décision de vous inscrire au programme d’informatique ?');
INSERT INTO t_questions (question_id, question)VALUES (36, 'Quelles raisons vous ont motivé à vous inscrire à un programme d’informatique de l’Université de Moncton (sélectionnez une ou plusieurs réponses) ?');
INSERT INTO t_questions (question_id, question)VALUES (37, 'Après votre baccalauréat en informatique appliquée, comptez-vous poursuivre vos études en maîtrise à l\'Université de Moncton ?');

